# Generated by Django 3.2.5 on 2021-09-10 19:37

import blackchatapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('product_image', models.FileField(upload_to=blackchatapp.models.product_image_path)),
                ('product_thumb', models.FileField(upload_to=blackchatapp.models.product_thumb_path)),
            ],
        ),
    ]
